// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMQV97qf_kYeAbeu4NLa47DT1VkAezKRg',
    appId: '1:477955767192:web:17ae778af552f31d7fc9ed',
    messagingSenderId: '477955767192',
    projectId: 'wallpix-3a886',
    authDomain: 'wallpix-3a886.firebaseapp.com',
    storageBucket: 'wallpix-3a886.appspot.com',
    measurementId: 'G-WV1TTRY6WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3EdpKRhVxsGQ5BE5xJoYwmZRbCAH3wAY',
    appId: '1:477955767192:android:3bba67e5edda4e1c7fc9ed',
    messagingSenderId: '477955767192',
    projectId: 'wallpix-3a886',
    storageBucket: 'wallpix-3a886.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTdk3BxdWA8DxRezFqUHITXFt3wMVoZfc',
    appId: '1:477955767192:ios:7c90ffab3fd346317fc9ed',
    messagingSenderId: '477955767192',
    projectId: 'wallpix-3a886',
    storageBucket: 'wallpix-3a886.appspot.com',
    iosBundleId: 'com.example.walllhang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTdk3BxdWA8DxRezFqUHITXFt3wMVoZfc',
    appId: '1:477955767192:ios:27e5a1ad8f86b84f7fc9ed',
    messagingSenderId: '477955767192',
    projectId: 'wallpix-3a886',
    storageBucket: 'wallpix-3a886.appspot.com',
    iosBundleId: 'com.example.walllhang.RunnerTests',
  );
}
